
api:
  wordpress:
    url: https://blog.olona.no/wp-json/wp/v2/
  rpg-encounter:
    url: https://rpg-encounter-server.herokuapp.com

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  flyway:
    enabled: true
    clean-on-validation-error: true
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: example01
    driverClassName: org.postgresql.Driver
    maxActive: 10
    maxIdle: 5
    minIdle: 2
    initialSize: 5
    removeAbandoned: true
