create table insured_entity_grouping
(
    ID                  int GENERATED by default AS IDENTITY (START with 1000 INCREMENT by 1) PRIMARY KEY,
    ENTITY_GROUP_ID     int, --foreign key
    ENTITY_CODE         varchar(20),
    SEQUENCE_NO         int,
    APPROVED_BY_USER_ID varchar(20),
    ENTERED_BY_USER_ID  varchar(20)

);
