create table insured_entity_group
(
    ID                  int GENERATED by default AS IDENTITY (START with 1000 INCREMENT by 1) PRIMARY KEY,
    ENTITY_GROUP_NAME   varchar(255),
    APPROVED_BY_USER_ID varchar(20),
    ENTERED_BY_USER_ID  varchar(20)

);
